#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$ROOT_DIR/compose.yaml"
CONFIG_FILE="${RAPID_INBOX_CONFIG_FILE:-$ROOT_DIR/.rapid-inbox-docker/rapid-inbox.env}"
PROJECT_NAME="${RAPID_INBOX_COMPOSE_PROJECT:-rapid-inbox}"
HEALTH_TIMEOUT_SECONDS="${RAPID_INBOX_HEALTH_TIMEOUT_SECONDS:-180}"
GENERATED_CONFIG=0

case "$CONFIG_FILE" in
    /*) ;;
    *) CONFIG_FILE="$ROOT_DIR/$CONFIG_FILE" ;;
esac
PENDING_CREDENTIALS_MARKER="${CONFIG_FILE}.credentials-pending"

die() {
    printf 'docker-deploy: %s\n' "$*" >&2
    exit 1
}

usage() {
    cat <<'EOF'
Usage: ./docker-deploy.sh [command]

Commands:
  up           Build and deploy Rapid Inbox (default).
  update       Pull fresh base images, rebuild, and deploy.
  status       Show HTTP and SMTP container status.
  logs [name]  Follow logs for all services or one service.
  credentials  Show the generated initial admin credentials.
  data-volume  Show the Docker volume name used by this project.
  down         Stop containers without deleting persisted data.
  help         Show this help.

The first deployment creates .rapid-inbox-docker/rapid-inbox.env with mode 0600.
Edit HTTP_PUBLISHED_* or SMTP_PUBLISHED_* there to change host bindings.
EOF
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

check_project_name() {
    [[ "$PROJECT_NAME" =~ ^[a-z0-9][a-z0-9_-]*$ ]] \
        || die "invalid RAPID_INBOX_COMPOSE_PROJECT: $PROJECT_NAME"
}

check_health_timeout() {
    if [[ ! "$HEALTH_TIMEOUT_SECONDS" =~ ^[0-9]+$ ]] \
        || (( HEALTH_TIMEOUT_SECONDS <= 0 )); then
        die "RAPID_INBOX_HEALTH_TIMEOUT_SECONDS must be a positive integer"
    fi
}

check_docker() {
    require_command docker
    docker compose version >/dev/null 2>&1 \
        || die "Docker Compose v2 is required (the 'docker compose' command)"
    docker info >/dev/null 2>&1 \
        || die "cannot connect to the Docker daemon"
}

generate_secret() {
    local byte_count="$1"
    od -An -N "$byte_count" -tx1 /dev/urandom | tr -d ' \n'
}

validate_published_port() {
    local name="$1"
    local value="$2"
    if [[ ! "$value" =~ ^[0-9]+$ ]] || (( value < 1 || value > 65535 )); then
        die "$name must be an integer from 1 through 65535"
    fi
}

ensure_config() {
    local config_dir
    config_dir="$(dirname -- "$CONFIG_FILE")"
    [[ ! -L "$config_dir" ]] \
        || die "refusing symlinked configuration directory: $config_dir"
    install -d -m 0700 "$config_dir"
    chmod 0700 "$config_dir"

    if [[ -L "$CONFIG_FILE" ]]; then
        die "refusing symlinked configuration file: $CONFIG_FILE"
    fi
    if [[ -L "$PENDING_CREDENTIALS_MARKER" ]]; then
        die "refusing symlinked credentials marker: $PENDING_CREDENTIALS_MARKER"
    fi
    if [[ -e "$PENDING_CREDENTIALS_MARKER" && ! -f "$PENDING_CREDENTIALS_MARKER" ]]; then
        die "credentials marker is not a regular file: $PENDING_CREDENTIALS_MARKER"
    fi
    if [[ -e "$CONFIG_FILE" ]]; then
        [[ -f "$CONFIG_FILE" ]] || die "configuration path is not a regular file: $CONFIG_FILE"
        chmod 0600 "$CONFIG_FILE"
        return
    fi

    require_command od
    require_command mktemp

    local http_port="${RAPID_INBOX_HTTP_PORT:-8000}"
    local smtp_port="${RAPID_INBOX_SMTP_PORT:-25}"
    validate_published_port RAPID_INBOX_HTTP_PORT "$http_port"
    validate_published_port RAPID_INBOX_SMTP_PORT "$smtp_port"

    local temporary_file
    local temporary_marker
    local bootstrap_password
    local cursor_secret
    local metrics_token
    temporary_file="$(mktemp "$config_dir/.rapid-inbox.env.XXXXXX")"
    temporary_marker="$(mktemp "$config_dir/.credentials-pending.XXXXXX")"
    bootstrap_password="$(generate_secret 24)"
    cursor_secret="$(generate_secret 48)"
    metrics_token="$(generate_secret 32)"

    umask 077
    {
        printf '%s\n' '# Generated by docker-deploy.sh. Keep this file private.'
        printf 'BOOTSTRAP_ADMIN_USERNAME=admin\n'
        printf 'BOOTSTRAP_ADMIN_PASSWORD=%s\n' "$bootstrap_password"
        printf 'API_CURSOR_SECRET=%s\n' "$cursor_secret"
        printf 'METRICS_ENABLED=true\n'
        printf 'METRICS_TOKEN=%s\n' "$metrics_token"
        printf 'HTTP_CONCURRENCY_LIMIT=1000\n'
        printf 'LOG_LEVEL=INFO\n'
        printf 'LOG_FORMAT=json\n'
        printf 'REQUEST_LOG_ENABLED=true\n'
        printf 'INGEST_DURABLE_ACK=true\n'
        printf 'HTTP_PUBLISHED_ADDRESS=127.0.0.1\n'
        printf 'HTTP_PUBLISHED_PORT=%s\n' "$http_port"
        printf 'SMTP_PUBLISHED_ADDRESS=0.0.0.0\n'
        printf 'SMTP_PUBLISHED_PORT=%s\n' "$smtp_port"
    } >"$temporary_file"
    chmod 0600 "$temporary_file"
    printf '%s\n' 'generated_by=docker-deploy.sh' >"$temporary_marker"
    chmod 0600 "$temporary_marker"
    mv -f -- "$temporary_marker" "$PENDING_CREDENTIALS_MARKER"
    mv -f -- "$temporary_file" "$CONFIG_FILE"
    GENERATED_CONFIG=1
    printf 'Created private Docker configuration: %s\n' "$CONFIG_FILE"
}

config_value() {
    local key="$1"
    awk -F= -v wanted="$key" '$1 == wanted { sub(/^[^=]*=/, ""); print; exit }' "$CONFIG_FILE"
}

compose() {
    RAPID_INBOX_CONFIG_FILE="$CONFIG_FILE" \
        docker compose \
        --project-directory "$ROOT_DIR" \
        --project-name "$PROJECT_NAME" \
        --env-file "$CONFIG_FILE" \
        --file "$COMPOSE_FILE" \
        "$@"
}

container_health() {
    local service="$1"
    local container_id
    container_id="$(compose ps -q "$service" 2>/dev/null || true)"
    if [[ -z "$container_id" ]]; then
        printf 'missing'
        return
    fi
    docker inspect \
        --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' \
        "$container_id" 2>/dev/null || printf 'missing'
}

wait_for_health() {
    local service="$1"
    local deadline=$((SECONDS + HEALTH_TIMEOUT_SECONDS))
    local status
    while (( SECONDS < deadline )); do
        status="$(container_health "$service")"
        case "$status" in
            healthy)
                return 0
                ;;
            unhealthy|exited|dead)
                printf 'docker-deploy: %s became %s\n' "$service" "$status" >&2
                compose logs --tail=80 "$service" >&2 || true
                return 1
                ;;
        esac
        sleep 2
    done
    printf 'docker-deploy: timed out waiting for %s health\n' "$service" >&2
    compose logs --tail=80 "$service" >&2 || true
    return 1
}

rollout() {
    local pull_base_images="$1"
    check_project_name
    ensure_config
    if [[ "$GENERATED_CONFIG" -eq 1 ]]; then
        printf 'Initial credentials are stored safely. If deployment fails, run:\n'
        printf '  ./docker-deploy.sh credentials\n'
    fi
    check_docker
    check_health_timeout

    printf 'Building the deployment image before stopping the running services...\n'
    if [[ "$pull_base_images" -eq 1 ]]; then
        compose build --pull
    else
        compose build
    fi

    # Both processes share one PID namespace because the durable maintenance
    # protocol records and probes OS process IDs. The named volume is retained.
    compose stop --timeout 120 app
    compose up --detach --no-deps --force-recreate app
    if ! wait_for_health app; then
        die "the app did not become healthy; persisted data was retained"
    fi

    local http_address
    local http_port
    http_address="$(config_value HTTP_PUBLISHED_ADDRESS)"
    http_port="$(config_value HTTP_PUBLISHED_PORT)"
    case "$http_address" in
        0.0.0.0) http_address=127.0.0.1 ;;
        ::) http_address='[::1]' ;;
    esac

    printf '\nRapid Inbox is healthy.\n'
    printf 'Admin login: http://%s:%s/admin/login\n' "$http_address" "$http_port"
    printf 'SMTP is published on port %s.\n' "$(config_value SMTP_PUBLISHED_PORT)"
    compose ps app
    if [[ -e "$PENDING_CREDENTIALS_MARKER" || -L "$PENDING_CREDENTIALS_MARKER" ]]; then
        [[ -f "$PENDING_CREDENTIALS_MARKER" && ! -L "$PENDING_CREDENTIALS_MARKER" ]] \
            || die "credentials marker is not a regular file: $PENDING_CREDENTIALS_MARKER"
        # Remove first so an interrupted terminal write cannot automatically
        # print the same bootstrap secret again on a later deployment.
        rm -f -- "$PENDING_CREDENTIALS_MARKER"
        printf '\nGenerated admin username: %s\n' "$(config_value BOOTSTRAP_ADMIN_USERNAME)"
        printf 'Generated admin password (shown once): %s\n' \
            "$(config_value BOOTSTRAP_ADMIN_PASSWORD)"
    else
        printf 'Run ./docker-deploy.sh credentials to view the initial login values.\n'
    fi
}

show_credentials() {
    [[ -f "$CONFIG_FILE" && ! -L "$CONFIG_FILE" ]] \
        || die "Docker configuration does not exist; run ./docker-deploy.sh first"
    printf 'Admin username: %s\n' "$(config_value BOOTSTRAP_ADMIN_USERNAME)"
    printf 'Initial admin password: %s\n' "$(config_value BOOTSTRAP_ADMIN_PASSWORD)"
}

command_name="${1:-up}"
case "$command_name" in
    up)
        rollout 0
        ;;
    update)
        rollout 1
        ;;
    status)
        [[ -f "$CONFIG_FILE" ]] \
            || die "Docker configuration does not exist; run ./docker-deploy.sh first"
        check_docker
        check_project_name
        compose ps app
        ;;
    logs)
        [[ -f "$CONFIG_FILE" ]] \
            || die "Docker configuration does not exist; run ./docker-deploy.sh first"
        check_docker
        check_project_name
        shift
        compose logs --follow --tail=200 "$@"
        ;;
    credentials)
        show_credentials
        ;;
    data-volume)
        check_project_name
        printf '%s_rapid-inbox-data\n' "$PROJECT_NAME"
        ;;
    down)
        [[ -f "$CONFIG_FILE" ]] \
            || die "Docker configuration does not exist; run ./docker-deploy.sh first"
        check_docker
        check_project_name
        compose down --remove-orphans
        printf 'Rapid Inbox containers stopped. The named data volume was retained.\n'
        ;;
    help|-h|--help)
        usage
        ;;
    *)
        usage >&2
        die "unknown command: $command_name"
        ;;
esac
