#include <cstdlib>
#include <exception>
#include <iostream>
#include <stdexcept>
#include <string>

namespace test {
inline void check(bool condition, const std::string& message) {
    if (!condition) {
        throw std::runtime_error(message);
    }
}
}

void test_config_defaults();
void test_config_dotenv_and_environment_override();
void test_time_and_path_parts();
void test_ids_have_expected_prefixes();
void test_sha256_known_digest();
void test_storage_paths_match_python_layout();
void test_json_escape();
void test_mime_parser_text_only_message();
void test_mime_parser_html_only_message();
void test_mime_parser_multipart_alternative();
void test_mime_parser_attachment_base64();
void test_mime_parser_inline_related_part();
void test_mime_parser_decodes_quoted_printable_text();
void test_mime_parser_decodes_encoded_subject();
void test_mime_parser_reports_malformed_multipart();
void test_mime_parser_allows_boundary_trailing_whitespace();
void test_mime_parser_decodes_latin1_text_body();
void test_mime_parser_truncates_preview_at_utf8_boundary();
void test_mime_parser_replaces_invalid_utf8_in_preview();
void test_mime_parser_keeps_empty_attachment();
void test_mime_parser_decodes_gbk_encoded_subject();
void test_mime_parser_failure_is_std_exception();
void test_verification_code_extracts_plain_six_digit_code();
void test_verification_code_extracts_chinese_code();
void test_verification_code_extracts_grouped_digit_code();
void test_verification_code_extracts_alphanumeric_code();
void test_verification_code_extracts_html_openai_code();
void test_verification_code_ignores_order_number();
void test_verification_code_ignores_ambiguous_two_codes();
void test_verification_code_extracts_numeric_html_entities();
void test_verification_code_ignores_spaced_currency_value();
void test_verification_code_ignores_date_fragments();
void test_domain_matcher_exact_subdomain_and_longest_suffix();
void test_domain_matcher_plus_and_case_modes();
void test_domain_matcher_enforces_mailbox_syntax_and_length_limits();
void test_domain_matcher_normalizes_unicode_domain_to_idna();
void test_domain_matcher_uses_explicit_catch_all_as_fallback();
void test_domain_cache_loads_active_rules();
void test_domain_cache_respects_matcher_flags();
void test_domain_cache_loads_plus_and_case_modes();
void test_domain_cache_reload_sees_rule_changes();
void test_domain_cache_snapshots_domain_policies();
void test_domain_cache_snapshots_matcher_and_policies_together();
void test_sqlite_db_applies_pragmas();
void test_sqlite_db_rejects_database_without_wal();
void test_sqlite_db_cleans_up_after_constructor_failure();
void test_sqlite_statement_step_done_rejects_rows();
void test_sqlite_statement_reset_clears_bindings();
void test_sqlite_statement_outliving_db_closes_connection();
void test_mail_queue_capacity_and_close();
void test_mail_queue_try_push_accepts_lvalues_and_rvalues();
void test_mail_queue_close_wakes_waiting_pop_batch();
void test_mail_queue_enforces_byte_capacity_and_reservations();
void test_mail_queue_maintenance_pause_linearizes_new_reservations();
void test_mail_queue_grows_byte_reservations_without_consuming_message_slots();
void test_mail_queue_group_commit_wait_collects_arrivals();
void test_ingest_app_isolates_poison_message_and_drains();
void test_ingest_app_hot_reloads_domains();
void test_ingest_app_enforces_storage_root_singleton_lifecycle();
void test_ingest_app_retries_rejected_metric_flush_without_loss();
void test_ingest_app_heartbeat_and_token_bound_drain_ack();
void test_ingest_instance_lock_rejects_competitor_and_releases_cleanly();
void test_ingest_instance_lock_is_cross_process_and_crash_safe();
void test_logger_parses_configuration_and_levels();
void test_logger_renders_single_line_json_and_redacts_secrets();
void test_logger_renders_single_line_text();
void test_logger_preserves_valid_utf8_when_bounding_fields();
void test_smtp_session_accepts_valid_message();
void test_smtp_session_advertises_esmtp_and_supports_noop();
void test_smtp_session_refuses_vrfy_without_disclosing_input();
void test_smtp_session_parses_mail_and_rcpt_esmtp_parameters();
void test_smtp_session_rejects_declared_size_at_recipient_policy();
void test_smtp_session_enforces_smtputf8_parameter();
void test_smtp_session_reserves_bytes_in_chunks_and_defers_pressure_response();
void test_smtp_session_defers_overlong_data_line_failure_to_terminator();
void test_smtp_session_attaches_domain_policy_snapshot();
void test_smtp_session_rejects_unknown_domain();
void test_smtp_session_counts_only_dashboard_recipient_rejections();
void test_smtp_session_rejects_prefix_collision_commands();
void test_smtp_session_clears_transaction_after_queueing();
void test_smtp_session_rejects_rcpt_before_mail_from();
void test_smtp_session_accepts_null_reverse_path_and_preserves_state_on_invalid_mail();
void test_smtp_session_rejects_data_arguments();
void test_smtp_session_discards_oversized_data_until_terminator();
void test_smtp_session_reports_queue_full();
void test_smtp_session_deduplicates_canonical_recipients();
void test_smtp_session_persists_pending_artifacts_before_durable_ack();
void test_smtp_session_keeps_durable_ownership_when_queue_closes_after_data();
void test_smtp_session_applies_domain_message_size_limit();
void test_smtp_session_respects_cross_process_maintenance_lock();
void test_smtp_session_releases_data_reservation_on_disconnect();
void test_smtp_server_stop_wakes_idle_client();
void test_smtp_server_idle_client_times_out();
void test_smtp_server_rejects_connections_over_limit();
void test_smtp_server_closes_overlong_lines();
void test_smtp_server_serves_esmtp_capabilities_and_pipeline_over_socket();
void test_smtp_server_rate_limits_connections_by_peer_ip();
void test_smtp_server_supports_ipv6_loopback_bind();
void test_smtp_server_defers_overlong_data_response_over_socket();
void test_smtp_server_refreshes_domain_rules_at_mail_boundaries();
void test_batch_writer_writes_raw_and_manifest();
void test_batch_writer_writes_quarantine_error_record();
void test_batch_writer_writes_private_storage_permissions();
void test_batch_writer_manifest_includes_domain_policy_snapshot();
void test_batch_writer_missing_domain_policy_rejects_without_creating_database();
void test_batch_writer_uses_job_policy_without_touching_database();
void test_batch_writer_ignores_preexisting_part_symlinks();
void test_batch_writer_writes_sqlite_parsed_records();
void test_batch_writer_marks_parse_failure_without_rejecting_raw();
void test_batch_writer_aggregates_minute_metrics_idempotently();
void test_batch_writer_accumulates_rejected_metrics();
void test_batch_writer_writes_parsed_attachment_records();
void test_batch_writer_upgrades_catch_all_mailbox_without_downgrade();
void test_batch_writer_merges_catch_all_canonical_collision();
void test_batch_writer_reuses_sqlite_session_and_recovers_after_failure();
void test_batch_writer_reconnects_after_database_file_replacement();
void test_batch_writer_revalidates_domain_identity_before_commit();

int main() {
    try {
        test_config_defaults();
        test_config_dotenv_and_environment_override();
        test_time_and_path_parts();
        test_ids_have_expected_prefixes();
        test_sha256_known_digest();
        test_storage_paths_match_python_layout();
        test_json_escape();
        test_mime_parser_text_only_message();
        test_mime_parser_html_only_message();
        test_mime_parser_multipart_alternative();
        test_mime_parser_attachment_base64();
        test_mime_parser_inline_related_part();
        test_mime_parser_decodes_quoted_printable_text();
        test_mime_parser_decodes_encoded_subject();
        test_mime_parser_reports_malformed_multipart();
        test_mime_parser_allows_boundary_trailing_whitespace();
        test_mime_parser_decodes_latin1_text_body();
        test_mime_parser_truncates_preview_at_utf8_boundary();
        test_mime_parser_replaces_invalid_utf8_in_preview();
        test_mime_parser_keeps_empty_attachment();
        test_mime_parser_decodes_gbk_encoded_subject();
        test_mime_parser_failure_is_std_exception();
        test_verification_code_extracts_plain_six_digit_code();
        test_verification_code_extracts_chinese_code();
        test_verification_code_extracts_grouped_digit_code();
        test_verification_code_extracts_alphanumeric_code();
        test_verification_code_extracts_html_openai_code();
        test_verification_code_ignores_order_number();
        test_verification_code_ignores_ambiguous_two_codes();
        test_verification_code_extracts_numeric_html_entities();
        test_verification_code_ignores_spaced_currency_value();
        test_verification_code_ignores_date_fragments();
        test_domain_matcher_exact_subdomain_and_longest_suffix();
        test_domain_matcher_plus_and_case_modes();
        test_domain_matcher_enforces_mailbox_syntax_and_length_limits();
        test_domain_matcher_normalizes_unicode_domain_to_idna();
        test_domain_matcher_uses_explicit_catch_all_as_fallback();
        test_domain_cache_loads_active_rules();
        test_domain_cache_respects_matcher_flags();
        test_domain_cache_loads_plus_and_case_modes();
        test_domain_cache_reload_sees_rule_changes();
        test_domain_cache_snapshots_domain_policies();
        test_domain_cache_snapshots_matcher_and_policies_together();
        test_sqlite_db_applies_pragmas();
        test_sqlite_db_rejects_database_without_wal();
        test_sqlite_db_cleans_up_after_constructor_failure();
        test_sqlite_statement_step_done_rejects_rows();
        test_sqlite_statement_reset_clears_bindings();
        test_sqlite_statement_outliving_db_closes_connection();
        test_mail_queue_capacity_and_close();
        test_mail_queue_try_push_accepts_lvalues_and_rvalues();
        test_mail_queue_close_wakes_waiting_pop_batch();
        test_mail_queue_enforces_byte_capacity_and_reservations();
        test_mail_queue_maintenance_pause_linearizes_new_reservations();
        test_mail_queue_grows_byte_reservations_without_consuming_message_slots();
        test_mail_queue_group_commit_wait_collects_arrivals();
        test_ingest_app_isolates_poison_message_and_drains();
        test_ingest_app_hot_reloads_domains();
        test_ingest_app_enforces_storage_root_singleton_lifecycle();
        test_ingest_app_retries_rejected_metric_flush_without_loss();
        test_ingest_app_heartbeat_and_token_bound_drain_ack();
        test_ingest_instance_lock_rejects_competitor_and_releases_cleanly();
        test_ingest_instance_lock_is_cross_process_and_crash_safe();
        test_logger_parses_configuration_and_levels();
        test_logger_renders_single_line_json_and_redacts_secrets();
        test_logger_renders_single_line_text();
        test_logger_preserves_valid_utf8_when_bounding_fields();
        test_smtp_session_accepts_valid_message();
        test_smtp_session_advertises_esmtp_and_supports_noop();
        test_smtp_session_refuses_vrfy_without_disclosing_input();
        test_smtp_session_parses_mail_and_rcpt_esmtp_parameters();
        test_smtp_session_rejects_declared_size_at_recipient_policy();
        test_smtp_session_enforces_smtputf8_parameter();
        test_smtp_session_reserves_bytes_in_chunks_and_defers_pressure_response();
        test_smtp_session_defers_overlong_data_line_failure_to_terminator();
        test_smtp_session_attaches_domain_policy_snapshot();
        test_smtp_session_rejects_unknown_domain();
        test_smtp_session_counts_only_dashboard_recipient_rejections();
        test_smtp_session_rejects_prefix_collision_commands();
        test_smtp_session_clears_transaction_after_queueing();
        test_smtp_session_rejects_rcpt_before_mail_from();
        test_smtp_session_accepts_null_reverse_path_and_preserves_state_on_invalid_mail();
        test_smtp_session_rejects_data_arguments();
        test_smtp_session_discards_oversized_data_until_terminator();
        test_smtp_session_reports_queue_full();
        test_smtp_session_deduplicates_canonical_recipients();
        test_smtp_session_persists_pending_artifacts_before_durable_ack();
        test_smtp_session_keeps_durable_ownership_when_queue_closes_after_data();
        test_smtp_session_applies_domain_message_size_limit();
        test_smtp_session_respects_cross_process_maintenance_lock();
        test_smtp_session_releases_data_reservation_on_disconnect();
        test_smtp_server_stop_wakes_idle_client();
        test_smtp_server_idle_client_times_out();
        test_smtp_server_rejects_connections_over_limit();
        test_smtp_server_closes_overlong_lines();
        test_smtp_server_serves_esmtp_capabilities_and_pipeline_over_socket();
        test_smtp_server_rate_limits_connections_by_peer_ip();
        test_smtp_server_supports_ipv6_loopback_bind();
        test_smtp_server_defers_overlong_data_response_over_socket();
        test_smtp_server_refreshes_domain_rules_at_mail_boundaries();
        test_batch_writer_writes_raw_and_manifest();
        test_batch_writer_writes_quarantine_error_record();
        test_batch_writer_writes_private_storage_permissions();
        test_batch_writer_manifest_includes_domain_policy_snapshot();
        test_batch_writer_missing_domain_policy_rejects_without_creating_database();
        test_batch_writer_uses_job_policy_without_touching_database();
        test_batch_writer_ignores_preexisting_part_symlinks();
        test_batch_writer_writes_sqlite_parsed_records();
        test_batch_writer_marks_parse_failure_without_rejecting_raw();
        test_batch_writer_aggregates_minute_metrics_idempotently();
        test_batch_writer_accumulates_rejected_metrics();
        test_batch_writer_writes_parsed_attachment_records();
        test_batch_writer_upgrades_catch_all_mailbox_without_downgrade();
        test_batch_writer_merges_catch_all_canonical_collision();
        test_batch_writer_reuses_sqlite_session_and_recovers_after_failure();
        test_batch_writer_reconnects_after_database_file_replacement();
        test_batch_writer_revalidates_domain_identity_before_commit();
        std::cout << "ingestd_tests ok\n";
        return EXIT_SUCCESS;
    } catch (const std::exception& exc) {
        std::cerr << "ingestd_tests failed: " << exc.what() << "\n";
        return EXIT_FAILURE;
    }
}
